### obtener todos las categories
GET http://localhost:3000/api/categories

### obtener una category
GET http://localhost:3000/api/categories/669ee14b9de875456ec4e49c

### crear una nueva category
POST http://localhost:3000/api/categories
Content-Type: application/json

{
    "nombre": "Accesorios para cafe",
    "descripcion": "Los mejores accesorios para tu cafe!"
    }

### modificar una category
PUT http://localhost:3000/api/categories/669ee14b9de875456ec4e49c
Content-Type: application/json

{
    "nombre": "Categoria modificada",
    "descripcion": "Esta categoria fue modificada..."
}

### modificar una category(parcialmente)
PATCH http://localhost:3000/api/categories/669ee14b9de875456ec4e49c
Content-Type: application/json

{
    "nombre": "Cafe e infusiones",
    "descripcion": "Una gran variedad"
}

### delete una category

DELETE http://localhost:3000/api/categories/669ef23e60a0b035bf470c56