### obtain all brands
GET http://localhost:3000/api/brands

### obtain one brand
GET http://localhost:3000/api/brand/a02b91bc-3769-4221-beb1-d7a3aeba7dad

### create a new brand
POST http://localhost:3000/api/brands
Content-Type: application/json

{
    "nombre": "Cafernium",
    "descripcion": "Coffee from the future"
    }

### update one brand
PUT http://localhost:3000/api/brands/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{
    "nombre": "Cafernium 2.0",
    "descripcion": "Cafernium reloaded..."
}

### upgrade one brand(partially)
PATCH http://localhost:3000/api/brands/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{
    "nombre": "Cafernium Forward",
    "descripcion": "A new thing"
}

### delete one brand

DELETE http://localhost:3000/api/brands/a02b91bc-3769-4221-beb1-d7a3aeba7dad