### GET ALL
GET http://localhost:3000/api/product/classes

### POST
# @name createProductClass
POST http://localhost:3000/api/product/classes
Content-Type: application/json

{
  "name": "Whole Grain",
  "description": "Taste the flavor of the coffee"
}

### ID
@id = {{createProductClass.response.body.data.id}}

### GET ONE
GET http://localhost:3000/api/product/classes/{{id}}

### PUT

PUT http://localhost:3000/api/product/classes/{{id}}
Content-Type: application/json

{
    "name": "Granos enteros",
    "description": "Prueba el sabor del cafe"
}

### POST CLASS TO DELETE
# @name createProductClassToDelete
POST http://localhost:3000/api/product/classes
Content-Type: application/json

{
    "name":"prueba",
    "description":"descripcion de prueba borraduki"
}

### DELETE

@idToDelete = {{createProductClassToDelete.response.body.data.id}}

DELETE http://localhost:3000/api/product/classes/{{idToDelete}}