### GET all products
GET http://localhost:3000/api/products

### POST a product
# @name newCafe
POST http://localhost:3000/api/products
Content-Type: application/json

{
    "nombre": "cafe nuevo",
    "productClass": " ",
    "descripcion": "cafe dorado",
    "precio": "500",
    "stock": "1",
    "marca": "Leyenda",
    "categoria": "Unico"
    }

### ID
@id = {{newCafe.response.body.data.id}}

### GET one product
GET http://localhost:3000/api/products/{{id}}

### PUT a product
PUT http://localhost:3000/api/products/{{id}}
Content-Type: application/json

{
    "nombre": "cafe put",
    "descripcion": "cafe plateado",
    "precio": "999",
    "stock": "33",
    "marca": "Epico",
    "categoria": "Unico"
}

### POST a product
POST http://localhost:3000/api/products
Content-Type: application/json

{
    "nombre": "cafe fuerte",
    "descripcion": "cafe de sabor robusto",
    "precio": "1234",
    "stock": "312",
    "marca": "El mas rico",
    "categoria": "Importado"
}

### POST a product
# @name createProductToDelete
POST http://localhost:3000/api/products
Content-Type: application/json

{
    "nombre": "cafe nuevo",
    "ProductClass": "6531d6cfdc98243fffeB41ec",
    "descripcion": "cafe dorado",
    "precio": "1000",
    "stock": "10",
    "marca": "Veloz",
    "categoria": "Importado"
}

### DELETE a product
@idToDelete = {{createProductToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/products/{{idToDelete}}

### PATCH a product (parcialmente)
PATCH http://localhost:3000/api/products/{{idToDelete}}
Content-Type: application/json

{
    "nombre": "cafe put",
    "descripcion": "cafe INCREIBLE"
}

### DELETE a product

DELETE http://localhost:3000/api/products/{{idToDelete}}