### GET ALL
GET http://localhost:3000/api/product/brands

### POST
# @name createProductBrand
POST http://localhost:3000/api/product/brands
Content-Type: application/json

{
    "nombre": "Capsula pequengfgfdia",
    "descripcion": "Una capsulgfdgdfa de cafe"
}

### ID
@id = {{createProductBrand.response.body.data.id}}

### GET ONE
GET http://localhost:3000/api/product/brands/{{id}}

### PUT
PUT http://localhost:3000/api/product/brands/{{id}}
Content-Type: application/json

{
    "nombre": "Capsula grande", 
    "descripcion": "capsula de cafeeeee"
}

### POST CATEGORY TO DELETE
# @name createProductBrandToDelete
POST http://localhost:3000/api/product/brands
Content-Type: application/json

{
    "nombre":"prueba",
    "descripcion":"descripcion de prueba borraduki"
}

### DELETE
@idToDelete = {{createProductBrandToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/product/brands/{{idToDelete}}