### obtener todos los products
GET http://localhost:3000/api/products

### crear un nuevo product
# @name createMarca
POST http://localhost:3000/api/products
Content-Type: application/json

{
    "nombre": "cafe nuevo",
    "descripcion": "cafe dorado",
    "precio": "500",
    "stock": "1",
    "productBrand": "66f9e07932a1f21b48b88858",
    "productClass": "Unico"
    }


### ID
@id = {{createMarca.response.body.data.id}}

### obtener una category
GET http://localhost:3000/api/products/{{id}}


### modificar un product
PUT http://localhost:3000/api/products
Content-Type: application/json

{
    "nombre": "cafe put",
    "descripcion": "cafe plateado",
    "precio": "999",
    "stock": "33",
    "productBrand": "66f9e07932a1f21b48b88858",
    "productClass": "Unico"
}

### POST a product
# @name createProductToDelete
POST http://localhost:3000/api/products
Content-Type: application/json

{
    "nombre": "cafe nuevo 2",
    "descripcion": "cafe marron",
    "precio": "568",
    "stock": "17",
    "productBrand": "Epico",
    "productClass": "Unico"
}

### modificar un product(parcialmente)
PATCH http://localhost:3000/api/products/{{idToDelete}}
Content-Type: application/json

{
    "nombre": "cafe viejo",
    "descripcion": "cafe dorado antiguo",
    "productBrand": "Leyenda"

}

### DELETE a product
@idToDelete = {{createProductToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/products/{{idToDelete}}