### obtener todos los products
GET http://localhost:3000/api/products

### crear un nuevo product
# @name createMarca
POST http://localhost:3000/api/products
Content-Type: application/json

{
    "nombre": "cafe",
    "descripcion": "cafe dorado",
    "precio": "500",
    "stock": "1",
    "productBrand": "66fb074181af8e4453b3acd1",
    "productClass": "66fae7dc1c0b7c05cbef0a65"
    }


### ID
@id = {{createMarca.response.body.data.id}}

### obtener un producto
GET http://localhost:3000/api/products/{{id}}


### modificar un producto
PUT http://localhost:3000/api/products/{{id}}
Content-Type: application/json

{
    "nombre": "cafe nuevo",
    "descripcion": "cafe dorado",
    "precio": "520",
    "stock": "1",
    "productBrand": "66fb0c5c5d936014378bc66f",
    "productClass": "66feb67230181c7b5123acf7"
    }


### POST a product
# @name createProductToDelete
POST http://localhost:3000/api/products
Content-Type: application/json

{
    "nombre": "cafe viejo",
    "descripcion": "cafe marronazo",
    "precio": "777",
    "stock": "17",
    "productBrand": "66fdbbac58cee0737b5d0582",
    "productClass": "66feb7dab4d80d202502fdc9"
}

### modificar un product(parcialmente)
PATCH http://localhost:3000/api/products/{{idToDelete}}
Content-Type: application/json

{
    "nombre": "cafe viejo",
    "descripcion": "cafe dorado antiguo",
    "productBrand": "66feb47443bc4542470f0252"

}

### DELETE a product
@idToDelete = {{createProductToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/products/{{idToDelete}}